main: cc.altoya.settlements.App
name: settlements
version: 0
folia-supported: true
api-version: 1.20
description: Settlements plugin

commands:
  commandName:
    description: description
    usage: /command {var} {var}